CREATE TABLE IF NOT EXISTS auth (
  id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
  access_token VARCHAR(30) NOT NULL,
  refresh_token VARCHAR(50) NOT NULL,
  expiry INT(5),
  generated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
, CHECK (expiry >= 0));
